// Builds a Mermaid flowchart of one case's branching, for docs/graphs/<case>.md.
// Pure: compiled case in, Markdown out. The ideal path for each setting is drawn in bold.
import { idealRun } from '../engine/engine.ts';
import type { Condition, Grade, Next, Node } from './schema.ts';
import type { CompiledCase } from './types.ts';

const GRADE_MARK: Record<Grade, string> = { best: '✓', acceptable: '~', suboptimal: '↓', harmful: '✗' };

const safeId = (id: string) => 'n_' + id.replace(/[^A-Za-z0-9_]/g, '_');
const clip = (s: string, n = 34) => (s.length > n ? s.slice(0, n - 1) + '…' : s);
/** Mermaid-safe label text. */
const esc = (s: string) =>
  s.replace(/"/g, '#quot;').replace(/</g, '#lt;').replace(/>/g, '#gt;').replace(/\|/g, '/');

export function conditionText(c: Condition): string {
  if ('flag' in c) return c.flag;
  if ('notFlag' in c) return `not ${c.notFlag}`;
  if ('setting' in c) return c.setting;
  if ('all' in c) return c.all.map(conditionText).join(' and ');
  if ('any' in c) return c.any.map(conditionText).join(' or ');
  if ('not' in c) return `not (${conditionText(c.not)})`;
  const what = 'vital' in c ? c.vital : 'patient meter';
  return [c.below !== undefined && `${what} < ${c.below}`, c.above !== undefined && `${what} > ${c.above}`]
    .filter(Boolean)
    .join(' and ');
}

function nodeLabel(id: string, n: Node): string {
  const kind = n.type === 'ecg-leads' ? 'tap leads' : n.type;
  const text =
    'prompt' in n ? n.prompt : n.type === 'ending' ? n.outcome.toUpperCase() : (n.panels[0]?.caption ?? '');
  const shown = text ? clip(text.replace('{clock} · ', '')) : '';
  return `<b>${esc(id)}</b><br/><i>${kind}</i>${shown ? `<br/>${esc(shown)}` : ''}`;
}

function shape(id: string, n: Node): string {
  const l = `"${nodeLabel(id, n)}"`;
  switch (n.type) {
    case 'story':
      return `${safeId(id)}([${l}])`;
    case 'ending':
      return `${safeId(id)}[[${l}]]:::${n.outcome}`;
    default:
      return `${safeId(id)}[${l}]:::decision`;
  }
}

interface Edge {
  from: string;
  to: string;
  labels: string[];
  harmful: boolean;
}

function edgesOf(id: string, n: Node): Edge[] {
  const out = new Map<string, Edge>();
  const add = (to: string, label: string, harmful = false) => {
    const e = out.get(to) ?? { from: id, to, labels: [], harmful: false };
    if (label) e.labels.push(label);
    e.harmful ||= harmful;
    out.set(to, e);
  };
  const addNext = (next: Next | undefined, prefix: string, harmful = false) => {
    if (!next) return;
    if (typeof next === 'string') return add(next, prefix, harmful);
    for (const b of next)
      add(b.to, [prefix, b.if ? `if ${conditionText(b.if)}` : next.length > 1 ? 'otherwise' : ''].filter(Boolean).join(' · '), harmful);
  };
  if ('options' in n && n.type !== 'multiselect')
    for (const o of n.options) addNext(o.next, `${GRADE_MARK[o.grade]} ${clip(o.label, 28)}`, o.grade === 'harmful');
  if (n.type === 'dose') {
    addNext(n.correct.next, 'correct dose');
    addNext(n.under.next, 'underdose');
    addNext(n.over.next, 'overdose', true);
  }
  if (n.type === 'calculator') {
    addNext(n.correct.next, 'score right');
    addNext(n.close.next, 'same band');
    addNext(n.wrong.next, 'wrong band');
  }
  if (n.type === 'ecg-leads') {
    addNext(n.correct.next, 'all leads right');
    addNext(n.partial.next, 'partly right');
    addNext(n.wrong.next, 'wrong leads');
  }
  if ('next' in n) addNext(n.next, '');
  return [...out.values()];
}

export function caseGraph(c: CompiledCase): string {
  const lines = ['flowchart TD'];
  for (const [id, n] of Object.entries(c.nodes)) lines.push(`  ${shape(id, n)}`);
  const edges = Object.entries(c.nodes).flatMap(([id, n]) => edgesOf(id, n));
  edges.forEach((e) => {
    const label = e.labels.length ? `|"${esc(e.labels.slice(0, 3).join(' / ') + (e.labels.length > 3 ? ' …' : ''))}"|` : '';
    lines.push(`  ${safeId(e.from)} -->${label} ${safeId(e.to)}`);
  });

  const settings = c.settings.length ? c.settings.map((s) => s.id) : [null];
  const idealPaths = settings.map((s) => ({ setting: s, path: idealRun(c, s).path }));
  const idealPairs = new Set(idealPaths.flatMap(({ path }) => path.slice(1).map((to, i) => `${path[i]}>${to}`)));
  edges.forEach((e, i) => {
    if (idealPairs.has(`${e.from}>${e.to}`)) lines.push(`  linkStyle ${i} stroke-width:4px`);
    else if (e.harmful) lines.push(`  linkStyle ${i} stroke:#c62828,stroke-dasharray:4 3`);
  });
  lines.push(
    '  classDef decision stroke-width:2px',
    '  classDef good stroke:#1a1915,stroke-width:3px',
    '  classDef fair stroke:#8a877d,stroke-width:3px',
    '  classDef critical stroke:#c62828,stroke-width:3px',
  );

  const md = [
    `# ${c.id}: ${c.title}`,
    '',
    '_Generated by `npm run graph`; do not edit by hand._',
    '',
    'Shapes: rounded = story, box = decision, double box = ending (red border = critical).',
    'Arrow marks: ✓ best · ~ acceptable · ↓ suboptimal · ✗ harmful (red dashed). **Bold arrows = ideal path.**',
    '',
    '```mermaid',
    ...lines,
    '```',
    '',
    '## Ideal path',
    '',
    ...idealPaths.map(({ setting, path }) => `- **${setting ?? 'all settings'}:** ${path.join(' → ')}`),
    '',
  ];
  return md.join('\n');
}
