// npm run review — writes docs/CLINICAL_REVIEW.md: every clinical item that still needs the
// content owner's verification, grouped by file, with its source and any TODO.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { compileContent, ContentError } from '../src/content/compile.ts';

let compiled;
try {
  compiled = compileContent(process.cwd());
} catch (e) {
  if (e instanceof ContentError) {
    console.error(`✗ Fix content problems first (npm run validate):\n${e.message}`);
    process.exit(1);
  }
  throw e;
}

const refs = new Map(compiled.references.map((r) => [r.id, r.citation]));
const pending = compiled.checks.filter((c) => !c.verified);
const byFile = new Map<string, typeof pending>();
for (const c of pending) byFile.set(c.file, [...(byFile.get(c.file) ?? []), c]);
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

const out: string[] = [
  '# Clinical review checklist',
  '',
  '_Generated by `npm run review` — do not edit by hand._',
  '',
  `Content version \`${compiled.index.version}\`. **${pending.length}** of ${compiled.checks.length} clinical items are unverified.`,
  '',
  'How to verify an item: open the file at the line shown, check the content against the source,',
  'then change its `check:` to `verified: true` and add `reviewedOn: YYYY-MM-DD` (today). Only the content owner does this.',
  '',
];
for (const [file, items] of byFile) {
  out.push(
    `## ${file}`,
    '',
    '| ✓ | Line | Where | What | Source | TODO |',
    '|---|---|---|---|---|---|',
  );
  for (const i of items)
    out.push(
      `| ☐ | ${i.line} | \`${cell(i.where)}\` | ${cell(i.what)} | ${i.source.map((s) => `\`${s}\``).join(', ')} | ${cell(i.todo ?? '')} |`,
    );
  out.push('');
}
const noted = compiled.checks.filter((c) => c.verified && c.todo);
if (noted.length) {
  out.push(
    '## Verified, but still carrying a note',
    '',
    'These items are marked verified; their `todo` notes are kept here so nothing is lost. Delete a note once it is resolved.',
    '',
    '| Line | File | Where | Note | Reviewed |',
    '|---|---|---|---|---|',
  );
  for (const i of noted)
    out.push(
      `| ${i.line} | ${i.file} | \`${cell(i.where)}\` | ${cell(i.todo ?? '')} | ${i.reviewedOn ?? ''} |`,
    );
  out.push('');
}
const needsSource = compiled.checks.filter((c) => c.source.includes('needs-source'));
if (needsSource.length) {
  out.push('## Items with no source yet (`needs-source`)', '');
  for (const i of needsSource) out.push(`- ${i.file}:${i.line} \`${i.where}\`: ${cell(i.what)}`);
  out.push('');
}
const allRefs = new Set(pending.flatMap((p) => p.source));
if (allRefs.size) {
  out.push('## Sources cited above', '');
  for (const r of [...allRefs].sort())
    out.push(`- \`${r}\`${refs.has(r) ? ` — ${refs.get(r)}` : ''}`);
  out.push('');
}

const path = join(process.cwd(), 'docs', 'CLINICAL_REVIEW.md');
mkdirSync(join(process.cwd(), 'docs'), { recursive: true });
writeFileSync(path, out.join('\n'));
console.log(`Wrote docs/CLINICAL_REVIEW.md — ${pending.length} item(s) to verify.`);
